
import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Particles from '@/components/Particles';
import { Upload, FileImage, FileVideo, FileAudio } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

const Detect = () => {
  const { toast } = useToast();
  
  const handleUpload = () => {
    toast({
      title: "Coming Soon",
      description: "The full detection feature will be available in the next update.",
      duration: 3000,
    });
  };

  return (
    <div className="min-h-screen bg-sc-dark text-white">
      <Particles />
      <Navbar />
      <main className="pt-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-5xl mx-auto py-12">
          <h1 className="text-4xl font-bold mb-6 text-center">Detect AI-Generated Content</h1>
          <p className="text-xl text-gray-300 mb-12 text-center max-w-3xl mx-auto">
            Upload your files for instant analysis and discover if they've been altered or generated by AI.
          </p>
          
          <div className="glass-card p-8 mb-12">
            <div className="flex flex-col items-center">
              <Upload className="h-16 w-16 text-sc-blue mb-4" />
              <h2 className="text-2xl font-semibold mb-4">Upload Media for Analysis</h2>
              <p className="text-gray-400 mb-8 text-center max-w-xl">
                Drag and drop files here or click to browse. We support images, videos, and audio files.
              </p>
              
              <div className="flex flex-wrap gap-4 justify-center mb-8">
                <Button 
                  onClick={handleUpload}
                  className="bg-sc-blue text-black hover:bg-sc-blue/80 flex gap-2 items-center"
                >
                  <FileImage className="h-4 w-4" /> Upload Image
                </Button>
                <Button 
                  onClick={handleUpload}
                  className="bg-sc-violet text-black hover:bg-sc-violet/80 flex gap-2 items-center"
                >
                  <FileVideo className="h-4 w-4" /> Upload Video
                </Button>
                <Button 
                  onClick={handleUpload}
                  className="bg-sc-mint text-black hover:bg-sc-mint/80 flex gap-2 items-center"
                >
                  <FileAudio className="h-4 w-4" /> Upload Audio
                </Button>
              </div>
              
              <p className="text-sm text-gray-500 text-center">
                Max file size: 50MB. Your files are securely processed and never stored permanently.
              </p>
            </div>
          </div>
          
          <div className="mb-12">
            <h2 className="text-2xl font-semibold mb-6 text-center">How Our Detection Works</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="glass-card p-6">
                <h3 className="text-xl font-semibold mb-4 text-sc-blue">Image Analysis</h3>
                <ul className="list-disc list-inside space-y-2 text-gray-300">
                  <li>Pattern recognition detects AI-generated artifacts</li>
                  <li>Metadata examination reveals editing history</li>
                  <li>Pixel inconsistency identification</li>
                  <li>Neural network comparison with known AI generators</li>
                </ul>
              </div>
              
              <div className="glass-card p-6">
                <h3 className="text-xl font-semibold mb-4 text-sc-violet">Video/Audio Analysis</h3>
                <ul className="list-disc list-inside space-y-2 text-gray-300">
                  <li>Temporal consistency checking across frames</li>
                  <li>Voice pattern analysis for synthetic speech</li>
                  <li>Deepfake facial movement detection</li>
                  <li>Audio waveform irregularity identification</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Detect;
